import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from datetime import datetime
from components.utils import load_config
import re

# Constants for Gmail SMTP
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def markdown_to_html(text):
    """
    Simple converter to make the email look pretty without installing external libraries.
    """
    # Escape HTML to prevent injection (basic)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # Bold: **text** -> <b>text</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    
    # Headers: ### Header -> <h3>Header</h3>
    text = re.sub(r'^### (.*)', r'<h3 style="color: #2c3e50; margin-top: 20px;">\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.*)', r'<h2 style="color: #2c3e50; border-bottom: 1px solid #eee;">\1</h2>', text, flags=re.MULTILINE)

    # Bullet points: * item -> <li>item</li>
    # We wrap them in <ul> later or just accept simple styling
    text = re.sub(r'^\* (.*)', r'<li style="margin-bottom: 5px;">\1</li>', text, flags=re.MULTILINE)
    
    # Newlines to <br> (but not inside lists to avoid huge gaps)
    lines = text.split('\n')
    html_lines = []
    in_list = False
    
    for line in lines:
        if line.strip().startswith('<li'):
            if not in_list:
                html_lines.append('<ul>')
                in_list = True
            html_lines.append(line)
        else:
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append(f"{line}<br>")
            
    if in_list: html_lines.append('</ul>')
            
    return "\n".join(html_lines)


def send_alert(subject: str, markdown_body: str, video_title: str = None, video_url: str = None, dry_run: bool = False):
    """
    Sends the Intelligence Report via Email (Clean HTML formatting).
    """
    # Load user configuration
    config = load_config()
    receiver_email = config.get("email")
    sender_email = receiver_email  # Self-emailing
    sender_password = config.get("smtp_password")

    # Fallback if title wasn't passed
    display_title = video_title if video_title else subject

    print("📧 Preparing Notification...")

    # Convert the raw markdown report to pretty HTML
    formatted_body = markdown_to_html(markdown_body)
    
    # Construct the HTML body with a clickable link
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px;">
            <h2 style="color: #d9534f;">Here's an update!</h2>
            <p><strong>Analyzed:</strong> <a href="{video_url}" style="color: #0275d8; text-decoration: none; font-weight: bold;">{display_title}</a></p>
            <p style="font-size: 12px; color: #777;">Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div style="padding: 20px;">
            {formatted_body}
        </div>
        
        <hr style="border: 0; border-top: 1px solid #eee;">
        <p style="font-size: 12px; color: #999; text-align: center;">Generated by VoxGuard Autonomous Agent</p>
    </body>
    </html>
    """

    # Check credentials
    if dry_run or not receiver_email or not sender_password:
        filename = f"report_{datetime.now().strftime('%H%M%S')}.html"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html_body)
        print(f"⚠️ Email Config Missing or Dry Run. Saved locally: {filename}")
        return

    # Send Email
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = f"🚨 {subject}"  # Keeping the urgent subject line for the inbox!!
        msg.attach(MIMEText(html_body, 'html'))

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        
        print(f"✅ Email sent successfully to {receiver_email}")
        
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
